# Generated by Django 5.0.7 on 2024-08-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='domicilio',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
