# Generated by Django 5.0.7 on 2024-08-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0002_profesor_domicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='domicilio',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
